<img src=http://www.acofi.edu.co/eiei2016/wp-content/uploads/2016/09/Logo-Universidad-ICESI.jpg width="500" height="200" align="center">

#**<big><big>Matemáticas Aplicadas II</big></big><br><small>Depto. Ciencias Fisicas y aplicadas / Facultad de Ingeniería</small><br><small>Vectores. </small>**

**<u>Conceptos</u>**
*Operaciones con matrices*

#Operaciones con matrices









###Producto de una matriz por un escalar






La multiplicación escalar de matrices se define de manera similar a la de vectores, y es hecha multiplicando cada elemento de la matriz por el escalar.

In [ ]:
import numpy as np
vector_1 = [1,0,1,2,4]
vector_1 = [1,0,1,2,4]
vector_1 = [1,0,1,2,4]
vector_1 = [1,0,1,2,4]
matriz = np.array([[2, 4], [5, -6]])

In [ ]:
c=5
cA = np.multiply(A,c)

###Suma de matrices



Similarmente la suma de matrices del mismo tamaño se hace componente a componente, esto es, si $A=(A)_{ij}$ y $B=(B)_{ij}$ entonces $$C=(C)_{ij}=(A)_{ij}+(B)_{ij} $$




In [ ]:
S = A + B

###Producto matriz-vector



Si A es una matriz $m\times n$ y $x$ es un $n-$vector, entonces el producto matriz-vector $y = Ax$ es el $m-$vector $y$ con elementos

$$ y_i = \sum_{k=1}^n A_{ik}x_k=A_{i1}x_1+...+A_{in}x_n.,\quad i=1,...,m.$$



In [33]:
import numpy as np
vector_1 = [1,0,1,2,4]
vector_2 = [0,1,0,3,2]
vector_3 = [2,4,3,1,0]
vector_4 = [2,1,0,1,3]
matriz = np.array([vector_1,vector_2,vector_3,vector_4])
print(matriz)

[[1 0 1 2 4]
 [0 1 0 3 2]
 [2 4 3 1 0]
 [2 1 0 1 3]]


In [35]:
vector = [0,2,3,5,1]
matriz_resultado = matriz.dot(vector)
print(matriz_resultado)

[17 19 22 10]


###Producto matriz-matriz



Es posible multiplicar dos matrices $A$ y $B$ usando la multiplicación de matrices. siempre que sus dimensiones sean compatibles, lo que significa que elnúmero de columnas de $A$ es igual al número de filas de $B$. Supongamos que $A$ y $B$ son compatibles, por ejemplo, $A$ tiene tamaño $m\times p$ y $B$ tiene tamaño $p\times n$. Entonces la matriz del producto $C = AB$ es la matriz $m\times n$ con elementos

$$C_{ij}=\sum_{k=1}^? A_{ik}B_{kj}=A_{i1}B_{1j}+...+A_{ip}B_{pj}.,\quad i=1,...,m,\quad j=1,...,n.$$

In [29]:
import numpy as np
vector_1 = [1,0,1,2]
vector_2 = [0,1,0,3]
vector_3 = [2,4,3,1]
vector_4 = [2,1,0,1]
matriz_1 = np.array([vector_1,vector_2,vector_3,vector_4])
print(matriz_2)

[[1 0 1 2 4]
 [0 1 0 3 2]
 [2 4 3 1 0]
 [2 1 0 1 3]]


In [30]:
import numpy as np
vector_1 = [1,0,1,2,4]
vector_2 = [0,1,0,3,2]
vector_3 = [2,4,3,1,0]
vector_4 = [2,1,0,1,3]
matriz_2 = np.array([vector_1,vector_2,vector_3,vector_4])
print(matriz_1)

[[1 0 1 2]
 [0 1 0 3]
 [2 4 3 1]
 [2 1 0 1]]


In [32]:
matriz_producto = np.matmul(matriz_1,matriz_2)
print(matriz_producto)

[[ 7  6  4  5 10]
 [ 6  4  0  6 11]
 [10 17 11 20 19]
 [ 4  2  2  8 13]]


También se puede calcular el producto de matrices con el comando

```
A.dot(B)
```
* *$A$* es una matriz ${nxm}$
* *$B$* es una matriz ${mxp}$


###Matriz inversa



La matriz inversa de una matriz $A_{nxn}$ es una matriz cuadrada, representada por $A^{-1}_{nxn}$.

In [36]:
import numpy as np
vector = np.array([1,3,5,7,11])
matriz = np.diag(vector)
matriz_inv = np.linalg.inv(matriz)
print(matriz_inv)

[[1.         0.         0.         0.         0.        ]
 [0.         0.33333333 0.         0.         0.        ]
 [0.         0.         0.2        0.         0.        ]
 [0.         0.         0.         0.14285714 0.        ]
 [0.         0.         0.         0.         0.09090909]]


Se dice que $A^{-1}$ es la inversa de otra matriz cuadrada $A$ cuando el producto de ambas matrices es la matriz identidad.

In [37]:
import numpy as np
vector = np.array([1,3,5,7,11])
matriz = np.diag(vector)
matriz_inv = np.linalg.inv(matriz)
print(matriz.dot(matriz_inv))

[[1. 0. 0. 0. 0.]
 [0. 1. 0. 0. 0.]
 [0. 0. 1. 0. 0.]
 [0. 0. 0. 1. 0.]
 [0. 0. 0. 0. 1.]]
