<img src=http://www.acofi.edu.co/eiei2016/wp-content/uploads/2016/09/Logo-Universidad-ICESI.jpg width="500" height="200" align="center">

#**<big><big>Matemáticas Aplicadas II</big></big><br><small>Depto. Ciencias Fisicas y aplicadas / Facultad de Ingeniería</small><br><small>Vectores. </small>**

**<u>Conceptos</u>**
*Matrices, generalidades de matrices, matrices especiales*

#Matrices


> **Nota:** como se menciono anteriormente la descripción matemática de ciertos fenómenos del mundo real requiere de una colección de números, y que tales situaciones se abstraen en el concepto de  vector. Ahora, se construira otro objeto matemático compuesto por vectores para describir otras situaciones que involucran por ejemplo imágenes o grafos entre otros.

Las matrices generalmente se denotan con letras mayúsculas
rodeados por corchetes o paréntesis,

$$A=\left[\begin{array}{rrrr}
1.1&0.1&-0.5&100&1\\
0.0&0.2&-0.2&10&2\\
3.6&0.4&-0.1&1&3\\
7.2&0.8&0.0&0.1&4
\end{array}\right].$$


Los elementos (o entradas) de una matriz son los valores en el arreglo. El tamaño (también llamado dimensión) de una matriz viene dado por el número de vectores fila y columna que contiene. La matriz $A$ de arriba, por ejemplo, tiene  cuatro vectores fila y cinco vectores columna. Diremos que $A$ es una matriz $4\times 5$. Una matriz con $m$ filas y $n$ columnas tiene tamaño $m\times n$, se puede decir que pertenece a $\mathbb{R}^{m\times n}$.

#Generalidades

1.   Los elementos (o entradas o coeficientes) de una matriz son los valores del arreglo.
2. El elemento $i,j$ de la matriz, denotado $A_{ij}$ es el valor en la $i-$ésima fila y la $j-$ésima columna,

3. Dos matrices son iguales si tienen el mismo tamaño y las entradas correspondientes son todas iguales.
4. Una matriz cuadrada tiene el mismo número de filas y columnas $(m=n)$. Se dice que una matriz cuadrada de tamaño $n\times n$ es de orden $n$. Una *matriz alta* tiene más filas que columnas (tamaño $m\times n$ con $m > n$). Una *matriz ancha* tiene más
columnas que filas (tamaño $m\times n$ con $n > m$)
5. *Vectores columna y fila*. Un $n-$vector se puede interpretar como una matriz $n\times 1$. Una matriz con
solo una fila, es decir, con tamaño $1\times n$, se llama vector fila.

#Matrices especiales

###Matriz cero.


 Una matriz cero es una matriz con todos los elementos iguales a cero. La matriz cero de tamaño $m\times n$ a veces se escribe como $0_{m\times n}$, pero por lo general una matriz cero se denota solo $0$. En este caso, el tamaño de la matriz cero debe determinarse a partir del contexto. Comando en python.

```
np.zeros((a,b),dtype=int)
```
* $a$ cantidad de filas de la matriz.
* $b$ cantidad de columnas de la matriz.


In [ ]:
import numpy as np
np.zeros((3,2),dtype=int)


array([[0, 0],
       [0, 0],
       [0, 0]])

###Matriz fila y Matriz columna

si se desea trabajar con una matriz fila o columna solo es necesario cambiar las dimensiones

In [ ]:
import numpy as np
np.zeros((1,5),dtype=int)

array([[0, 0, 0, 0, 0]])

In [ ]:
import numpy as np
np.zeros((5,1),dtype=int)

array([[0],
       [0],
       [0],
       [0],
       [0]])

###Matriz identidad.


Una matriz  identidad es otra matriz cuadrada. Sus elementos diagonales, es decir, aquellos con índices de fila y columna iguales, son
todos iguales a uno, y sus elementos fuera de la diagonal (aquellos con índices fila y columna desiguales) son cero. Las matrices  identidad se denotan con la letra $I$ y se define por:

$$I_{ij}=\begin{cases}
1, & \text{ si } i=j \\
0, & \text{ si } i\not= j\end{cases}$$

comando para python
```
np.identity(n, dtype = None, like = None)
```


*  $n$, Es el número de filas y columnas de la matriz $(n x n)$
*  $dtype$, valor opcional. El tipo de variable de la matriz, por default es float.
* Like, valor opcional. Es una referencia para crear arreglos que no sean Numpy array.

In [ ]:
import numpy as np
np.identity(3, dtype = int, like = None )

array([[1, 0, 0],
       [0, 1, 0],
       [0, 0, 1]])

###Matrices diagonales


Una matriz $A$ cuadrada $n\times n$ es diagonal si $A_{ij} = 0$ para $i \not= j$. (Las entradas de una matriz con $i = j$ se denominan entradas diagonales; las que tienen $i \not= j$ son sus entradas fuera de la diagonal.). Ejemplos de matrices diagonales que ya hemos visto son cuadradas matrices cero y matrices identidad.

comando en python
```
np.diag(vector)
```
* $vector$ lista en python. Se crea una matriz diagonal cuadrada con los elementos del vector en la diagonal.

In [ ]:
import numpy as np
vector = np.array([1,3,5,7,11])
np.diag(vector)

array([[ 1,  0,  0,  0,  0],
       [ 0,  3,  0,  0,  0],
       [ 0,  0,  5,  0,  0],
       [ 0,  0,  0,  7,  0],
       [ 0,  0,  0,  0, 11]])

una vez creada la matriz se puede escoger submatrices de esta matriz.

In [ ]:
import numpy as np
vector = np.array([1,3,5,7,11])
matriz = np.diag(vector)
print(matriz[0:4,0:3])

[[1 0 0]
 [0 3 0]
 [0 0 5]
 [0 0 0]]


como se puede observar si la matriz formada tiene dimensiones $5x5$. No es posible escoger una sub-matriz con dimensiones mas grandes.

In [ ]:
import numpy as np
vector = np.array([1,3,5,7,11])
matriz = np.diag(vector)
print(matriz[0:7,0:4])

[[1 0 0 0]
 [0 3 0 0]
 [0 0 5 0]
 [0 0 0 7]
 [0 0 0 0]]


In [ ]:
import numpy as np
vector = np.array([1,3,5,7,11])
matriz = np.diag(vector)
print(matriz[0:4,0:9])

[[1 0 0 0 0]
 [0 3 0 0 0]
 [0 0 5 0 0]
 [0 0 0 7 0]]


###Matriz transpuesta



Si $A$ es una matriz $m\times n$, su transpuesta, denotada $A^T$ (o a veces $A'$ o $A^*$), es la
matriz de $n\times m$ dada por $(A^T)_{ij} = A_{ji}$. En otras palabras, las filas y columnas de $A$ son
transpuestas en $A^T$.

In [1]:
import numpy as np
vector_1 = [1,0,3,4,7]
vector_2 = [0,3,5,0,1]
vector_3 = [1,2,5,1,1]
vector_4 = [1,3,5,7,11]
matriz = np.array([vector_1,vector_2,vector_3,vector_4])
print(matriz)


[[ 1  0  3  4  7]
 [ 0  3  5  0  1]
 [ 1  2  5  1  1]
 [ 1  3  5  7 11]]


traspuesta de la matriz.

In [2]:
import numpy as np
vector_1 = [1,0,3,4,7]
vector_2 = [0,3,5,0,1]
vector_3 = [1,2,5,1,1]
vector_4 = [1,3,5,7,11]
matriz = np.array([vector_1,vector_2,vector_3,vector_4])
print(matriz.T)

[[ 1  0  1  1]
 [ 0  3  2  3]
 [ 3  5  5  5]
 [ 4  0  1  7]
 [ 7  1  1 11]]


###Matriz simétrica

una matriz $A$ es simétrica si $A=A^t$. En particular las matrices diagonales son simétricas.

In [ ]:
import numpy as np
vector = np.array([1,3,5,7,11])
matriz = np.diag(vector)
print(matriz.T)

[[ 1  0  0  0  0]
 [ 0  3  0  0  0]
 [ 0  0  5  0  0]
 [ 0  0  0  7  0]
 [ 0  0  0  0 11]]
